README.md, pyproject.toml, requirements.txt, setup.cfg, tests/test_ppo.py
This PR addresses package setup issues with the following updates:
- Adds package finding to `setup.cfg` to avoid "multiple top-level packages" errors during new environment installs. 
- __Related issue__: #41
- Updates `README.md` installation instructions to use `pip install -e ...`, as  `python setup.py ...` is deprecated and should be replaced with pip tools ([reference guide](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html)).
- Adds separate `dev` dependencies to `setup.cfg` to avoid forcing `dev` dependencies on package install.
- Adopts `pytest` as the test runner.
- Renames `unittests` to `tests` to avoid confusion with `unittest` module and adhere to common Python unit-test directory naming.
=> [update] Improve package setup

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/documentation.yml, .github/ISSUE_TEMPLATE/feature_request.yml
This PR adds initial issue templates to help organize/track issues in a consistent manner.
=> Add initial issue templates

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/documentation.yml, .github/workflows/build.yml, .github/workflows/code_quality.yml, trlx/model/accelerate_base_model.py, trlx/model/accelerate_ilql_model.py, trlx/model/accelerate_ppo_model.py, trlx/model/nn/ppo_models.py, trlx/orchestrator/offline_orchestrator.py, trlx/orchestrator/ppo_orchestrator.py, trlx/pipeline/accelerate_base_pipeline.py
This PR adds initial GitHub workflows for building, testing, and checking for code quality.
=> Add initial GitHub workflows

README.md
Hey there 👋 I've done a first review of the documentation.
For context, I've skimmed the documentation as a beginner to see where are the friction points.
There are some other improvements we can do, so I opened an issue so that we can discuss about it before doing another PR 🤗 .
The Issue: #65
=> Update documentation (first review)

.gitignore
This is a minor PR to add `ckpts/` dir name to the `.gitignore` file. I think while saving model the default dir name is `ckpts/`. I think this will keep the git status clean.
=> Add ckpt/ to gitignore

trlx/data/configs.py, trlx/model/accelerate_base_model.py
This PR adds support for the `entity` option in `wandb` logging to allow for finer control over which profile/team to log to.
=> Add `entity` name config for `wandb` logging

configs/ilql_config.yml, configs/ppo_config.yml, configs/ppo_gptj.yml, configs/test_config.yml, examples/randomwalks.py, trlx/data/configs.py, trlx/model/accelerate_base_model.py
This PR provides the following updates based on observations from issue #53:
- Adds the previously unused `weight_decay` TrainConfig parameter to `AccelerateRLModel` optimizer initialization.
- Adds an `opt_eps` TrainConfig parameter to the `AccelerateRLModel` to allow users to specify an optimizer's epsilon value.
- Renames `learning_rate_init` and `learning_rate_target` to `lr_init` and `lr_target` TrainConfigs, respectively, for consistency with learning rate naming conventions in `torch.optim` algorithms.
- Removes unused `lr_ramp_steps` and `lr_decay_steps` TrainConfig parameters which look to be leftovers from the [magicCARP lr scheduler](https://github.com/EleutherAI/magiCARP/blob/777a578abcf0f790b653d3bce9dcbff8f5cd6bd7/carp/util.py#L25).
=> Update `TrainConfig` optimizer hyperparameters

CONTRIBUTING.md
This PR adds a tip to the contribution guidelines, recommending contributors test their work on some of the examples provided in the repo.
=> Add examples tip to contribution guide

examples/ilql_sentiments.py, examples/ppo_sentiments.py
This PR
- truncates input into pipeline to bert's context length (512)
- puts pipeline on processes' local gpus for 2x speedup in training on single gpu (1:02 v 2:19 for 128 gradient steps), a bit more on multigpu (1:07 v 9:26 on 8 gpus) at cost of 0.5G extra VRAM
- removes depreciation warning of `return_all_scores` usage in pipeline, on transformers version `4.24.0`
=> Fix pipeline's context overflow

.pre-commit-config.yaml, trlx/data/method_configs.py, trlx/model/accelerate_ppo_model.py, trlx/model/nn/ppo_models.py, trlx/utils/modeling.py
This PR decouples the PPO loss function from the `AcceleratePPOModel` class for general reuse following @cat-state 's work in #75 . The following updates are also provided:
- Adds the unbiased KL-div estimates following http://joschu.net/blog/kl-approx.html
- Related Issue: #53 
- Removes repeated initialization of `self.kl_ctl` in `accelerate_ppo_models` constructor.
- Removes `utils.modeling.clip_by_value` as this functionality was added to PyTorch nearly 2 years ago.
- Introduces more PPO statistics to the logger for greater debugging information.
Test Run: https://wandb.ai/jon-tow/ppo-test
=> Refactor PPO objective function

configs/ilql_config.yml, examples/ilql_sentiments.py, trlx/model/nn/ilql_models.py
This pr
- puts pipeline on rank 0 gpu to process large validation batch sizes
- removes stats collection with `wandb.Histogram` during sampling, since it was redundant and also was slowing down validation
https://wandb.ai/sorry/public/runs/1u2vv56a
=> Fix slow ilql eval

README.md
The documentation for this library uses trLX instead of TRLX as the naming scheme. This PR updates the README to reflect the same.
=> Update README to align nomenclature correctness

configs/ppo_config.yml, trlx/model/nn/ppo_models.py, trlx/orchestrator/ppo_orchestrator.py, trlx/utils/modeling.py
In the spirit of #48
reward scaling from https://github.com/DLR-RM/stable-baselines3/blob/d5d1a02c15cdce868c72bbc94913e66fdd2efd3a/stable_baselines3/common/vec_env/vec_normalize.py#L220
minibatch whitening from https://github.com/openai/spinningup/blob/038665d62d569055401d91856abb287263096178/spinup/algos/pytorch/ppo/ppo.py#L80
https://wandb.ai/sorry/public/reports/mean_reward-22-11-17-01-59-30---VmlldzoyOTg0ODc3
=> Add optional reward scaling

configs/ilql_config.yml, configs/ppo_config.yml, configs/ppo_gptj.yml, configs/ray_tune_configs/ppo_config.yml, configs/test_config.yml, examples/experiments/grounded_program_synthesis/config/trlx_ppo_config.yml, trlx/trlx.py, trlx/utils/loading.py
This PR fixes the issue in which registered entities of `trlx` are not accessible by loading getters unless manually imported from higher-level calling sites by importing all such entities from `trlx/utils/loading.py`.
Updates:
- Fixes `ilql_config.yml` to use the proper `AccelerateILQLModel` type.
Notes:
- There isn't a distinction between `PPOPipeline` and `OfflinePipeline` anymore so I'm not sure if it's worth keeping that configuration option around.
=> Force class registry via imports

configs/ppo_config.yml, trlx/model/accelerate_base_model.py, trlx/model/nn/ppo_models.py, trlx/orchestrator/ppo_orchestrator.py, trlx/utils/__init__.py
This pr fixes #107 
- lets models in orchestrator use `attention_mask` for computing `old_logprobs`
but also
- removes entity_name from ppo_config (which I suspect wasn't intentional)
- enables more thorough logging, synced with orchestrator's logging with `iter_count`
- adds git commit as tag to wandb runs
https://wandb.ai/sorry/public/reports/Ratio-fix--VmlldzozMDE4NzI2
=> Fix ppo ratio inaccuracy

trlx/model/accelerate_base_model.py, trlx/trlx.py, trlx/utils/__init__.py
This PR adds RNG seeding across multiple dependencies to improve reproducible behavior. Previously, seeding was only configured through `torch.random.manual_seed` leading to variable runs between experiments with the same configuration.
* `wandb` logs: https://wandb.ai/jon-tow/trlx-seed/reports/branch-fix-seeding--VmlldzozMDQwOTU3?accessToken=9jbh76n9ur7khpdouyvftzo267gqd051k2z64mcej6cnhsuji921max2ee8d2952
=> Set RNG seeds across multiple dependencies

trlx/trlx.py
* `set_seed(config.train.seed)` fails if no config is passed to the `train` function as a default config must be created first.
=> Set seed after default config instantiation

configs/ppo_gptj.yml, examples/experiments/grounded_program_synthesis/configs/trlx_ppo_config.yml, examples/experiments/grounded_program_synthesis/lang.py, examples/experiments/grounded_program_synthesis/train_trlx.py, tests/test_configs.py
This PR adds the following configuration and example updates:
- Adds unit tests to ensure future config changes do not break examples. Note that this requires TRL config YAMLs to be located in directories named `configs`. (This might need to be updated _if_ we decide to integrate OmegaConf/Hydra for config management.)
- Adds method config options, `scale_reward`, `ref_mean`, `ref_std`, and `cliprange_reward` to appropriate PPO configs.
- Fixes `examples/experiments/grounded_program_synthesis` missing `dataset` directory error.
Awaiting #109
=> Add unit tests to ensure valid example configs

trlx/data/configs.py, trlx/model/accelerate_ppo_model.py, trlx/pipeline/ppo_pipeline.py
Adds the `rollout_logging_dir` parameter to `TrainConfig`, which when specified will triggering the saving generated rollouts at the end of each epoch.
See the relevant pull request in [algorithm distillation](project) to see how this can be used to collect rollouts over a hyperparameter sweep.
In future we should probably extend this to log to wandb artifacts.
=> Add local rollout logging

trlx/model/nn/ppo_models.py
This PR adds `GPTNeo`-based hydra heads for complete support of the EleutherAI model suite.
_Note_: `GPTNeo` follows the same model branch implementation as `GPTModelBranch` so there are no source changes.
`wandb` reports:
* [PPO sentiment](https://wandb.ai/jon-tow/trlx/reports/trlx-GPT-Neo-PPO-Sentiment---VmlldzozMDkxNzY2?accessToken=944j2mf4827ww9dudiktf7xb8yrzftnp20oip2nxftev9jxc9dsmwkadf9sw90cd)
* [ILQL sentiment](https://wandb.ai/jon-tow/trlx/reports/trlx-GPT-Neo-PPO-Sentiment--VmlldzozMDkxNzg4?accessToken=p7vk9yti9rf52futwyixu8847pz96z0rv01ilksi8dy7hta2qr319f5xjwrr9s51)
=> Add hydra head support for `GPTNeo`

trlx/model/nn/ppo_models.py
This PR adds hydra-based PPO model branching support for `BloomModel`s.
`wandb` reports:
* [PPO Sentiment](https://wandb.ai/jon-tow/bloom-trlx/reports/trlx-BLOOM-Hydra-Support-Sanity-Benchmark--VmlldzozMTExNzQx?accessToken=di165xkctf625t8szihzw87qpbnb71qjxit92dxjhkc4kbiragjnpoaxygt62k6a)
Note: The `<Arch>ModelBranch` implementations should be refactored in the future to share a common interface if we plan on adding more in the near future.
=> Add `BloomModel` hydra support

trlx/model/__init__.py, trlx/model/accelerate_base_model.py
After performing the example, the model that was save at `ckpts`
it call https://github.com/CarperAI/trlx/blob/1a3461d592a567409e11e3c47b5b355bf219449f/trlx/model/accelerate_base_model.py#L139
when I use `ckpts` weight it call https://github.com/CarperAI/trlx/blob/1a3461d592a567409e11e3c47b5b355bf219449f/trlx/model/__init__.py#L119
=> add: load function for AccelerateRLModel

configs/ilql_config.yml, configs/ppo_config.yml, configs/ppo_gptj.yml, configs/test_config.yml, examples/experiments/grounded_program_synthesis/configs/trlx_ppo_config.yml, examples/randomwalks/configs/ilql_randomwalks.yml, examples/randomwalks/configs/ppo_randomwalks.yml, tests/test_utils.py, trlx/data/configs.py, trlx/model/accelerate_base_model.py, trlx/utils/__init__.py
This PR adds the following configuration updates:
- Adds an `OptimizerConfig` dedicated to customizing optimizer specifications.
- Previously users were hard constrained to `torch.optim.AdamW`.
- This should make it easier to add other optimizers like 8-bit optimizers
introduced in PR #133
- Adds a `SchedulerConfig` for customizing the learning rate scheduler.
- Previously users were hard constrained to `torch.optim.lr_scheduler.CosineAnnealingLR`; this opens possibilities for other schedulers like `torch.optim.lr_scheduler.OneCycleLR` if desired from the community 
Notes:
- This PR formats the config YAML files throughout the repository to be more
consistent.
`wandb` reports: [PPO/ILQL Sentiments](https://wandb.ai/jon-tow/trlx/reports/trlx-Add-OptimizerConfig-and-SchedulerConfig-135--Vmll …
=> Add `OptimizerConfig` and `SchedulerConfig`

configs/ppo_config.yml, configs/ppo_gptj.yml
This PR removes my wandb login info and reverts the default ppo config optimizer to "adamw". I'm an idiot. 
Discovered by @reciprocated in #131 and prioritizing here.
=> Remove incorrect default config settings

configs/ilql_config.yml, configs/ppo_config.yml, configs/ppo_gptj.yml, examples/experiments/grounded_program_synthesis/configs/trlx_ppo_config.yml, examples/randomwalks/configs/ilql_randomwalks.yml, examples/randomwalks/configs/ppo_randomwalks.yml, trlx/model/accelerate_base_model.py, trlx/model/accelerate_ilql_model.py, trlx/model/accelerate_ppo_model.py, trlx/model/nn/ilql_models.py, trlx/model/nn/ppo_models.py, trlx/orchestrator/ppo_orchestrator.py, trlx/pipeline/offline_pipeline.py, trlx/trlx.py, trlx/utils/__init__.py, trlx/utils/modeling.py
Fix of #130, this PR
- limits generation's size to `max_new_tokens`
- truncates prompts to `seq_length - max_new_tokens`
- enables separate logging of prompts and generations
[PPO](https://wandb.ai/sorry/public/reports/Fix-context-overflow-131--VmlldzozMTUyMDI4)
[ILQL](https://wandb.ai/sorry/public/reports/Fix-context-overflow-131--VmlldzozMTUyMDU3)
=> Fix context overflow

trlx/utils/__init__.py
I overlooked this in the review of #141. With `LOCAL_RANK`, each device in a single node gets a unique seed but we probably want unique seeds across nodes as well for true device-specific seeding.
=> Set device-specific seeding with global rank

tests/test_ppo.py, trlx/model/nn/ppo_models.py
This PR updates the `ModelBranch` classes used in the PPO hydra architectures to freeze all parameters by default.
Currently, only the transformer blocks are frozen. Note that the `ModelBranch.lm_head`s are never frozen but the
`lm_head` they are `deepcopy`ed from are instead.
wandb report: [PPO](https://wandb.ai/jon-tow/trlx/reports/trlx-fix-frozen-branch-PR--VmlldzozMTY4Njc1)
=> Freeze hydra model branches 

trlx/trainer/accelerate_base_trainer.py
In this PR, learning rate is added to stats. Now it is easy to verify the LR scheduler work in wandb:
=> Logging learning rate

trlx/trainer/nn/ilql_models.py, trlx/trainer/nn/ppo_models.py
This pr enables usage of not pretrained transformers as base models, in particular it fixes [examples/randomwalks/ilql_randomwalks.py](https://github.com/CarperAI/trlx/blob/main/examples/randomwalks/ilql_randomwalks.py) which was broken previously.
[PPO/ILQL randomwalks runs with/without pretrain](https://wandb.ai/sorry/public/reports/Fix-instantiating-base-transformer-from-a-custom-config-149---VmlldzozMjA3OTAy)
=> Fix instantiating base transformer from a custom config

tests/test_utils.py, trlx/trainer/__init__.py, trlx/utils/__init__.py
In this PR:
- Linear LR scheduler is added. It was used in InstructGPT. From the [paper](https://arxiv.org/abs/2203.02155):
-  Tested with config:
```yaml
scheduler:
name: "linear"
kwargs:
start_factor: 0.1
end_factor: 1.0
total_iters: 64
```
- Some unused code is removed
=> Linear LR scheduler

.pre-commit-config.yaml, docs/source/conf.py, examples/architext.py, examples/experiments/grounded_program_synthesis/train_trlx.py, examples/ilql_sentiments.py, examples/ppo_sentiments.py, examples/randomwalks/ilql_randomwalks.py, examples/randomwalks/ppo_randomwalks.py, examples/simulacra.py, pyproject.toml, tests/test_configs.py, tests/test_ppo.py, trlx/data/configs.py, trlx/orchestrator/__init__.py, trlx/orchestrator/ppo_orchestrator.py, trlx/pipeline/__init__.py, trlx/pipeline/ppo_pipeline.py, trlx/ray_tune/train_funcs.py, trlx/ray_tune/wandb.py, trlx/sweep.py, trlx/trainer/accelerate_base_trainer.py, trlx/trainer/accelerate_ilql_trainer.py, trlx/trainer/accelerate_ppo_trainer.py, trlx/trainer/nn/ilql_models.py, trlx/trainer/nn/ppo_models.py, trlx/trlx.py, trlx/utils/loading.py, trlx/utils/modeling.py
This PR adds the following `pre-commit` updates:
* ~~Update `pre-commit-hook` to a more recent version.~~
* Adds `black` formatting to `tests` directory as it was never updated for the name change from `unittests`➡️`tests`
* Adds `isort` to the pre-commit action runner. This is to avoid waiting on #39 for the more involved `flake8` checks which will require working around `torchtyping`.
=> Update `pre-commit` version and add `isort`

tests/test_utils.py, trlx/data/configs.py, trlx/utils/modeling.py
* Makes `delta_kwargs` an optional config; previously it defaulted to an empty `dict` which breaks the delta handlers for runs that do not use delta-tuning. Discovered by @PhungVanDuy 
* Removes `gpt2` from the default `MODIFIED_MODULES_DICT` as its MLP layers are implemented as Conv1D layers which are not supported by the OpenDelta pacakge; see this line [here](https://github.com/thunlp/OpenDelta/blob/a25fb1b2aabb9a2ed55ca941a15b9321bb32377c/opendelta/delta_models/lora.py#L151) (Conv1D does not contain `in/out_features` attrs)
=> Fix default `delta_kwargs` handling

configs/sweeps/ilql_sweep.yml, configs/sweeps/ppo_sweep.yml, examples/ppo_sentiments.py, examples/summarize_daily_cnn/t5_summarize_daily_cnn.py, setup.cfg, trlx/ray_tune/wandb.py, trlx/trainer/accelerate_base_trainer.py
This PR checks for the `wandb` version to ensure `wandb.require("report-editing")` is used with the right version.
For `wandb` version > 0.13.5 `wandb.require` is not required and for `wandb` version < 0.12.21` it is not supported. 
This PR is to fix the original issue raised in #162 by @asmith26.
=> Fix wandb.errors.RequireError as reported in #162

examples/architext.py, examples/ilql_sentiments.py, examples/ppo_sentiments.py, examples/randomwalks/configs/ilql_randomwalks.yml, examples/randomwalks/ilql_randomwalks.py, examples/randomwalks/ppo_randomwalks.py, examples/summarize_daily_cnn/t5_summarize_daily_cnn.py, setup.cfg, trlx/orchestrator/ppo_orchestrator.py, trlx/ray_tune/wandb.py, trlx/trainer/__init__.py, trlx/trainer/accelerate_base_trainer.py, trlx/trainer/accelerate_ilql_trainer.py, trlx/trainer/accelerate_ppo_trainer.py, trlx/trlx.py, trlx/utils/__init__.py
This PR will
Among HF's `generate` arguments `StoppingCriteria` can only stop all generations per batch, `eos_token_ids` accepts only `List[int]`. The other option is to customize `generate` method for every architecture or to trim samples after `generate` as was done here
https://wandb.ai/sorry/trlx/reports/-Update-generation-utilities-172---VmlldzozMzIxMjE1
https://wandb.ai/sorry/trlx/reports/Update-generation-utilities-172--VmlldzozMzIxMjE5
=> Update generation utilities

trlx/data/configs.py, trlx/trainer/accelerate_base_trainer.py
* Adds the `group_name` option to training configs for `wandb` tracking. See the `Groups` filter in the project [here](https://wandb.ai/carperai/trlx).
* Related issue: #186
(Photo for quick viewing)
=> Add `wandb` group naming

README.md, examples/experiments/grounded_program_synthesis/train_trlx.py, examples/summarize_rlhf/configs/default_accelerate_config.yaml, examples/summarize_rlhf/trlx_gptj_text_summarization.py, examples/summarize_rlhf/trlx_inference_gptj.py, trlx/ray_tune/train_funcs.py
* Updates all examples with recent changes to expected `reward_fn` signature.
* Updates the RLHF example `accelerate` config to point to the correct `deepspeed_config_file` when running from the `summarize_rlhf` dir (as suggested in the README). Otherwise, it leads `FileNotFoundError: [Errno 2] No such file or directory: 'ds_config_trlx_gptj_summarize.json'`
=> Update `reward_fn` signatures in examples

configs/ilql_config.yml, configs/ppo_config.yml, configs/ppo_gptj.yml, configs/test_config.yml, examples/experiments/grounded_program_synthesis/configs/trlx_ppo_config.yml, examples/randomwalks/configs/ilql_randomwalks.yml, examples/randomwalks/configs/ppo_randomwalks.yml, examples/summarize_daily_cnn/configs/ppo_config_cnn_daily.yml, examples/summarize_rlhf/configs/ppo_config_summ_gptj.yml, tests/test_ppo.py, trlx/data/configs.py, trlx/orchestrator/offline_orchestrator.py, trlx/trainer/accelerate_base_trainer.py
This PR closes 
- #177
https://wandb.ai/sorry/trlx/reports/Difference-truncation_side-left-right--VmlldzozMzMwNTk5
=> Add tokenizer config

trlx/utils/__init__.py
This PR fixes `get_distributed_config` which previously always falsely reported "no" for `mixed_precision` when deepspeed was used
https://wandb.ai/sorry/trlx/runs/7gt7juhb
=> Fix extraction of `mixed_precision` option for deepspeed

examples/architext.py, examples/experiments/grounded_program_synthesis/train_trlx.py, examples/ilql_sentiments.py, examples/ppo_sentiments.py, examples/randomwalks/ilql_randomwalks.py, examples/randomwalks/ppo_randomwalks.py, examples/summarize_daily_cnn/t5_summarize_daily_cnn.py, examples/summarize_rlhf/trlx_gptj_text_summarization.py
Rewriting the config loading like this ensures that the examples can be called from anywhere. Moreover, file streams are properly closed after the file contents are retrieved.
=> Make the config loading consistent across all example scripts.

README.md, trlx/trainer/accelerate_base_trainer.py, trlx/trainer/accelerate_ilql_trainer.py, trlx/trainer/accelerate_ppo_trainer.py
* Makes the `Trainer.save_pretrained` `/hf_model` sub-directory optional. Previously, if a `directory` was supplied to `save_pretrained` the `hf_model` name path would be hard joined as `{directory}/hf_model`. Now users can directly write to the path defined by `directory` instead.
* Maybe the HF checkpoint dir should be an extra config? (Not sure if it's worth it).
* Corrects the repo `README.md` to properly document `save_pretrained` usage.
=> Make `Trainer.save_pretrained` sub-directory optional

README.md
I noticed the readme wasn't updated in PR https://github.com/CarperAI/trlx/pull/145, and doesn't include T5 models. Also thinking this is a last change to close out Issue https://github.com/CarperAI/trlx/issues/132
Not sure if this is important, well worded, too verbose, or if I'm missing other models now supported. Please let me know. Thanks.
=> Update Readme to include T5 models

trlx/data/configs.py
Currently `TRLConfig.update` will fail if given something like `{ "optimizer": { "name": "adam_8bit_bnb" } }"` since it'll check if the `optimizer` key is in `updates`, but `merge` won't add it because the only keys updated are nested. `merge` will check the keys to in every nested dict with the root level keys of the update config, which is problematic when changing an attr that is common across many subconfigs (e.g `"name"`), so this way allows proper nested updates.
=> Support nested updates in `merge`

trlx/trainer/accelerate_base_trainer.py
This bug was introduced by #209, which changed the `trackers` config property to `tracker` but didn't update this use case.
=> Fix undefined trackers property

trlx/data/configs.py
Fixes the missing property, which was breaking some use cases where hyperparameters are being tuned with Ray
Also orders alphabetically.
=> Fix tokenizer missing form config.to_dict()

examples/summarize_rlhf/trlx_gptj_text_summarization.py
In the specific config referenced by summarize_rlhf, it seems like the `model:` block does not have tokenizer_path. There does seem to be one in `tokenizer:` however.
=> read tokenizer path from config correctly

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
Add [Devcontainer](https://containers.dev/) support so that contributors can setup a working development environment with one click (e.g. with [GitHub Codespaces](https://github.com/features/codespaces) or [VS Code Remote Development Pack](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack)).
Includes CUDA support.
=> Add devcontainer support

trlx/data/configs.py
The example in config.py has lora_a = 0.5 as a parameter. The opendelta docs (and codebase) doesn't have a lora_a parameter, but does have lora_r. Which is the rank of the delta layers(?) and is an int. I am assuming this is intended.
```
config_dict = {
"delta_type":"lora", 
"modified_modules":[
"SelfAttention.q", 
"SelfAttention.v",
"SelfAttention.o"
], 
"lora_r":4}
delta_config = AutoDeltaConfig.from_dict(config_dict)
```
Otherwise with lora_a I get the following error:
```
carperAI_trlx_development  | Traceback (most recent call last):
carperAI_trlx_development  |   File "/opt/project/trlx/examples/summarize_daily_cnn/t5_summarize_daily_cnn.py", line 76, in <module>
carperAI_trlx_development  |     trlx.train(
carperAI_trlx_development  |   File "/opt/project/trlx/trlx/trlx.py", line …
```
=> fix: change lora_a:float to lora_r:int

.pre-commit-config.yaml
Bumps `isort` version in `pre-commit` to fix following errors:
```
stdout:
Processing /home/runner/.cache/pre-commit/repokeybmbqk
Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'done'
Preparing metadata (pyproject.toml): started
Preparing metadata (pyproject.toml): finished with status 'error'
stderr:
error: subprocess-exited-with-error
× Preparing metadata (pyproject.toml) did not run successfully.
│ exit code: 1
╰─> [14 lines of output]
Traceback (most recent call last):
File "/home/runner/.cache/pre-commit/repokeybmbqk/py_env-python3.8/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module> …
```
=> Bump `isort` to hotfix CI code quality workflow

trlx/trainer/accelerate_base_trainer.py
Fixes optional tracking error introduced in #226 in which the null tracker is never handled by `accelerate` (users must init the tracker with a `project_name` and is not simply a no-op)
Example config for `ppo_sentiments.py`:
```yaml
train:
seq_length: 1024
epochs: 100
total_steps: 10000
batch_size: 128
checkpoint_interval: 10000
eval_interval: 100
pipeline: "PromptPipeline"
orchestrator: "PPOOrchestrator"
trainer: "AcceleratePPOTrainer"
tracker: null  # REMOVE TRACKING
model:
model_path: "lvwerra/gpt2-imdb"
num_layers_unfrozen: 2
tokenizer:
tokenizer_path: "gpt2"
truncation_side: "right"
optimizer:
name: "adamw"
kwargs:
lr: 1.0e-4
betas: [0.9, 0.95]
eps: 1.0e-8
weight_decay: 1.0e-6
scheduler:
name: "cosine_annealing"
kwargs:
T_max: 10000 # train.total_steps
eta_min: 1.0e-4
method:
name: …
```
=> Fix optional tracking in `accelerator.log`

trlx/trainer/accelerate_base_trainer.py
Fix of https://github.com/CarperAI/trlx/issues/187, complete `stats` dictionary is only available on rank 0 and therefore previously all other processes were on the other side of this if statement https://github.com/CarperAI/trlx/blob/a02f806eb17288456e24c16f1e709d30d958b41b/trlx/trainer/accelerate_base_trainer.py#L511-L514
https://wandb.ai/sorry/trlx/runs/xv5mczq1/logs
(sidenote: these line breaks look dreadful, can we perhaps increase black's --line-length to something like 120?)
=> Fix deepspeed state saving under `save_best` condition

README.md
Addressing issue CarperAI/trlx#211, we've wrapped the [simulacra example](./examples/simulacra.py) in a functional colab notebook. This could be reproduced with the other examples.
=> added colab notebook

README.md, trlx/__init__.py, trlx/orchestrator/offline_orchestrator.py, trlx/orchestrator/ppo_orchestrator.py, trlx/trainer/accelerate_base_trainer.py, trlx/utils/__init__.py, trlx/utils/logging.py
This PR introduces a basic `logging.Logger` utility for status monitoring from the console with multi-process support. By default, the logger is set to the `INFO` level but verbosity can be controlled by setting the `TRLX_LOG_LEVEL` environment variable to one of the standard logging [level names](https://docs.python.org/3/library/logging.html#logging-levels). Check the `README.md` update for more. 
- Replaces prints with logger calls to allow for more control over when and how trlx messages are displayed to users. (`print_rank_0` is kept in utils as a debug tool)
- Adds logger info to indicate evaluation stages such as reward and metric function process during training #239 
- Re-introduces @PhungVanDuy 's  progress bar for evaluating batches of samples #178
=> Add multi-process logger utility for status monitoring

trlx/orchestrator/ppo_orchestrator.py, trlx/trainer/accelerate_base_trainer.py, trlx/trainer/accelerate_ppo_trainer.py
- Shards `eval_pipeline` (`accelerete.prepare(dataloader)` is a noop with deepspeed) to split evaluation sample between processes
- Trims redundant evaluation samples in case their number is not divisible by the number of processes multiplied by batch size (depends on recent fixes in the newest accelerate release 0.16.0)
- Shards prompt pipeline in `PPOOrchestrator` in the case of deepspeed (previously was sharded only for ddp)
- Unshards training pipeline in the case of ddp (previously only part of rollouts were used on each process during training)
https://wandb.ai/sorry/trlx/reports/Fix-distributed-dataloaders-deduplicate-eval-276---VmlldzozNDgzNDU3
These changes influenced training with both deepspeed & ddp by no more than correcting effective `batch_size` and `num_rollouts`. The …
=> Fix distributed dataloaders & deduplicate eval

trlx/trainer/accelerate_base_trainer.py
Fix of #238 
https://github.com/huggingface/accelerate/blob/4e5cc0c6b9c28fc569bfc70dd0508225d187fbf9/src/accelerate/utils/dataclasses.py#L527
https://wandb.ai/sorry/trlx/reports/-fix-Set-deepspeed-s-fp16-auto_cast-to-false-279--VmlldzozNDkzMzkx
Thanks @ZHAOTING for finding this fix
=> [fix] Set deepspeed's fp16 `auto_cast` to false

trlx/trainer/accelerate_ppo_trainer.py
* Removes lingering `logprobs_from_logits` from recent refactoring.
* ~~Adds condition to break out of PPORLElement collection to avoid "overflowing" the storage buffer. Previously, `make_experience` could generate and append more than the `num_rollouts` rollouts to the buffer leading to extended hangs. Reproduce with the following command and config (deepspeed zero-2):~~ 
`accelerate launch examples/ppo_sentiments.py`
```yaml
train:
seq_length: 612
epochs: 100
total_steps: 100000
batch_size: 6
checkpoint_interval: 10000
eval_interval: 100
save_best: False
pipeline: "PromptPipeline"
orchestrator: "PPOOrchestrator"
trainer: "AcceleratePPOTrainer"
tracker: null
model:
model_path: "google/flan-t5-small"
model_arch_type: "seq2seq"
num_layers_unfrozen: 2
tokenizer:
tokenizer_path: …
```
=> Rename remaining `logprobs_from_logits` call

configs/sft_config.yml, examples/architext.py, examples/ilql_sentiments.py, examples/randomwalks/ilql_randomwalks.py, examples/randomwalks/ppo_randomwalks.py, examples/sft_sentiments.py, examples/simulacra.py, examples/summarize_daily_cnn/t5_summarize_daily_cnn.py, examples/summarize_rlhf/trlx_gptj_text_summarization.py, trlx/trainer/accelerate_sft_trainer.py, trlx/trlx.py, trlx/utils/loading.py, trlx/utils/modeling.py
This PR gathers supervised finetuning from these two places[1][2] under the shared api
[1] https://github.com/CarperAI/trlx/blob/main/examples/summarize_rlhf/sft/train_gptj_summarize.py
[2] https://github.com/Dahoas/reward-modeling/blob/main/reward-modeling/finetune_base.py
https://wandb.ai/sorry/trlx/reports/Add-Accelerate-SFT-Trainer-280--VmlldzozNTAyNzQ1
=> [feat] Add Accelerate SFT Trainer

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
* Removes the `pip install pylance` command in the dev Dockerfile. This installs a dependency (https://pypi.org/project/pylance/) unrelated to Microsoft Pylance language server when it doesn't error out.
* Removes `"ms-python.vscode-pylance"` from customizations as it's already included in the installation of `"ms-python.python"` (https://marketplace.visualstudio.com/items?itemName=ms-python.python).
Related Issue: #295
CC @alan-cooney for any suggestions.
=> Remove `pylance` installs from devcontainer

trlx/trainer/accelerate_ppo_trainer.py
This PR lets PPO trainer to gather all experience samples on the main rank and to do a single joint reward_fn call per each rollout.
This enables hosting a single reward model on the same machine as the main rank, when previously every process had to had access to the reward model. Also it enables deliberate micro-batching for the reward model, unlike in the case when each process tries to infer reward model (for example deployed on Triton server) with its own small chunk_size number of samples usually bottle-necking whole training.
Main goal here is to give up the current dependency on the Triton server and to enable simple and self-contained 7+1(RM) or 15+1(RM) setups (can finally move to cw)
https://wandb.ai/sorry/trlx/reports/Gather-experience-samples-305---VmlldzozNTMxMzc3
Side-note: …
=> [feat] Gather experience samples

trlx/trainer/accelerate_base_trainer.py, trlx/utils/modeling.py
This PR makes `accelerate.gather_for_metrics` happen for each batch. Additionally elements of the batch are now padded to batch elements' max_length instead of global seq_length. And they are collected as lists, to avoid one big allocation (possibly bigger than RAM), since they don't have to be tensors afterwards.
https://wandb.ai/sorry/trlx/reports/Make-gather_for_metrics-more-strict-315--VmlldzozNTkyMTUy
=> [fix] Make `gather_for_metrics` usage more strict

tests/test_trainers.py, trlx/data/configs.py, trlx/trainer/__init__.py, trlx/trainer/accelerate_base_trainer.py
* Adds initial system for intermediate checkpointing into directories of the format: 
`{TrainConfig.checkpoint_dir}/checkpoint_{step}`
Related Issue: #348
=> Add intermediate checkpointing to `accelerate` trainers

examples/randomwalks/ilql_randomwalks.py, trlx/pipeline/offline_pipeline.py
This PR removes `<eos>` token from each sample's prompts & continuations and instead forces the last continuation to end with one, even in case of right truncation. 
https://wandb.ai/sorry/trlx-references/reports/fix-ilql-sample-endings-v-main--VmlldzozNzUyNzAw#ilql_randomwalks/gpt2config/1gpu
=> [fix] Drop `<eos>` from ILQL sample's phrases

trlx/trainer/accelerate_ilql_trainer.py
Fix of #368, previously `total_steps` were calculated against an unsharded dataloader, wrongly giving n-times bigger estimate of the number of gradient steps in the `tqdm` bar
=> [fix] ILQL `total_steps` calculation when running distributed

trlx/data/ppo_types.py
Logits are collapsed along vocab dimension for logprobs resulting in tensor shape `[..., response_size]`
https://github.com/CarperAI/trlx/blob/2f90ba0ecd640ae18cd62adb5e934a4b779f534b/trlx/trainer/accelerate_ppo_trainer.py#L433
Related Issue: #371
=> fix(docs): Update incorrect `PPORLElement` logprob tensor shape hint

trlx/models/modeling_base.py
This PR let's use a commit or branch for `AutoModel*.from_pretrained`'s model downloading. Previously
```python
model = AutoModelForCausalLMWithHydraValueHead.from_pretrained("EleutherAI/gpt-j-6B", revision="float16")
```
would try to download files from the `main` branch, instead of a revision passed into `from_pretrained_kwargs`
=> [fix] Enable HF downloads from a revision

setup.cfg, trlx/models/modeling_ilql.py
This PR fixes a bug where ILQL target heads were never being updated on the most recent accelerate & deepspeed versions. Removal of the chain iterator is not just a refactor, it fixed updates on heads from being only temporary and not persistent
https://wandb.ai/sorry/trlx/reports/-fix-Fix-ILQL-head-sync-under-ZeRO3-387---VmlldzozODc1MjI2
=> [fix] Fix ILQL head sync under ZeRO3

trlx/trainer/accelerate_base_trainer.py, trlx/trainer/accelerate_ppo_trainer.py
This PR fixes #399 and #373 by keeping `<|endoftext|>` token if it was outputted by the model (previously it was treated as if it was one of `stop_sequences`) and replacing trimming after-and-including `stop_sequences` with `<|endoftext|>`, instead of simply discarding them. This lets PPO's `make_experience` never filter any empty outputs, or in the worst case, stuck and timeout.
https://wandb.ai/sorry/trlx-references/reports/fix-preserve-eos-token-v-main--VmlldzozOTE1MDU2
=> [fix] Preserve `<eos>` token and in-place it after trimming

examples/simulacra.py
Hi, I'm running the simulacra example just to make sure that our distributed setup works with the TRLX examples, and it seems there is a bit of a race condition with respect to downloading the db, so I added some logic for only local rank 0 to download the db, and a barrier after the download. Let me know if there is another way you prefer to handle this (e.g. we could use sleep for a less reliable solution if you don't want to introduce an accelerate dependency in this example). Thanks!
Screenshot of single and multi node runs
=> Add some synchronization to the db download in the simulacra example

tests/test_minibatch.py, trlx/pipeline/__init__.py, trlx/trainer/accelerate_base_trainer.py
This adds compatibility for ILQL, SFT and PPO
=> Minibatch iterator

tests/test_models.py
Tests were breaking due to one of the `self._create_inputs` in the model tests not doing this
=> Set pad_token for all tokenizers in tests

trlx/trainer/accelerate_base_trainer.py, trlx/trainer/accelerate_ppo_trainer.py, trlx/trainer/accelerate_sft_trainer.py
The values of some items in the stats dictionary are tensors in the current code, and it prevents a tensorboard accelerate tracker from logging them.
This PR converts those tensors into scalars via `.item()` and makes the tensorboard tracker behave as expected.
=> Convert tensors in the stats dict into scalars

examples/ppo_translation_t5.py, trlx/trainer/accelerate_base_trainer.py
This PR has 2 changes:
1. Adds `examples/ppo_translation_t5.py`. Which shows an example of finetuning a T5 model for sequence, optimizing for COMET which is a neural metric trained to correlate with Human judgements. Should work for any HF translation model as well.
2. Small change to the `trlx/trainer/accelerate_base_trainer.py` to allow for agreggated metrics to be logged during training. This is needed when reporting corpus level metrics for evaluation.
=> Add Translation Finetuning Example with T5

.github/workflows/build.yml
Use the pinned dependencies in `requirements.txt` for unit testing in CI re discussion in the recent trlx meeting.
=> fix(CI): use pinned deps for CI testing

trlx/trainer/accelerate_sft_trainer.py
Fix of #426, the same error as in #374
=> fix(sft_trainer): `total_steps` calculation when running distributed

trlx/data/configs.py, trlx/models/modeling_base.py, trlx/trainer/accelerate_base_trainer.py
This PR lets users optionally choose whether to save optimizer state on each and a final checkpoint or only the model weights via `trainer.save_pretrained` (new default). Also this PR removes two back to back calls to `trainer.evaluate`, which would happen on the same `iter_count` in the case `total_steps` is divisible by `config.train.eval_interval`. And it fixes `trainer.save_pretrained`, in which under zero3, weights weren't gathered previously into the `state_dict`.
https://wandb.ai/sorry/trlx-references/reports/fix-save-pretrained-zero3-v-main--Vmlldzo0MDI1ODk1
=> fix(base_trainer): gather weights in `save_pretrained` under zero3

tests/test_pipelines.py, trlx/pipeline/offline_pipeline.py
This PR fixes a bug under which it was possible to run into negative indices with tokenizer's left truncation
https://wandb.ai/sorry/trlx/runs/yn59xu9i
=> fix(offline_pipeline): ILQL negative indexing under truncation

scripts/accelerate_train_example.sh, scripts/slurm_train.sh
Example scripts that run `examples/ilql_sentiments.py` on stability AWS cluster. Should work for other examples
Supports multi-node training.
Based on script from @reciprocated
=> Create Example training scripts to run in Stability cluster

examples/hh/README.md, trlx/models/modeling_ppo.py
This PR fixes the below error during PPO training, by generating the correct `position_ids` when it is None.
The PPO training was launched by:
```sh
accelerate launch --num_processes 7 --config_file ../../configs/accelerate/zero2-bf16.yaml ppo_hh.py
```
The below error was raised:
```
Traceback (most recent call last):
File "/data00/home/lijiahao.plus/deepspeed/trlx/examples/hh/ppo_hh.py", line 227, in <module>
main(hparams)
File "/data00/home/lijiahao.plus/deepspeed/trlx/examples/hh/ppo_hh.py", line 216, in main
trlx.train(
File "/data00/home/lijiahao.plus/deepspeed/trlx/trlx/trlx.py", line 103, in train
trainer.make_experience(config.method.num_rollouts)
File "/data00/home/lijiahao.plus/deepspeed/trlx/trlx/trainer/accelerate_ppo_trainer.py", line 408, in make_experience
ref_logits = …
```
=> fix(ppo_gpt): prevent position_ids being None

trlx/trainer/accelerate_base_trainer.py
If we do `trainer.evaluate()` before `trainer.learn()`, it will rasie `AttributeError` like:
```
│ ❱ 310 │   │   if self.generate_sweep_kwarg is not None:                                          │
│   311 │   │   │   gen_sweep_arg, gen_sweep_values = self.generate_sweep_kwarg                    │
│   312 │   │   else:                                                                              │
│   313 │   │   │   gen_sweep_values = [None]                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'AccelerateILQLTrainer' object has no attribute 'generate_sweep_kwarg'
```
so, I think it's better to initialize `generate_sweep_kwarg` with the initialization of the `trainer`
And …
=> fix(trainer): init self.generate_sweep_kwarg at self.__init__

trlx/trainer/accelerate_base_trainer.py
Ensure trailing EOS token is added also when the generated output contains trailing padding as is often the case when doing batch generation. When doing batched generations, some generated samples will end earlier than other samples. The samples that ended earlier will (in the case of T5/MT5) contain trailing `<pad>` tokens. The `sample[-1]` test to check if the last token of the sample is `<eos>` only works when the `<eos>` token comes last, which is only true for the longest of the generated samples.
=> Ensure trailing EOS token is added correctly for shorter generated outputs

examples/ilql_sentiments_t5.py, examples/ppo_sentiments_t5.py, examples/ppo_translation_t5.py, trlx/pipeline/offline_pipeline.py, trlx/pipeline/ppo_pipeline.py, trlx/trainer/accelerate_ppo_trainer.py, trlx/trlx.py
The default T5 tokenizer will generate padded `input_ids` tensors like below (0 is BOS and PAD token, 1 is EOS token)
```
prompt = ["Some prompt</s><pad><pad>", "A longer prompt</s>"]
input_ids = [[123, 345, ..., 1, 0, 0], [543, 123, ..., 1]]
```
I think there was two issues that might cause the inputs to T5 to be a bit different than what the model is trained for
* The T5 example scripts didn't configure the `padding_side` for the tokenizer, so it defaults to "left" which caused prompts to be left-padded instead of right-padded
* The `PromptPipeline` class applied `add_special_tokens=False` when tokenizing prompts, causing the EOS `</s>` to not be added to the prompt for seq2seq models
=> Pad prompts to the right in T5 examples and add EOS token to seq2seq prompts

trlx/trainer/accelerate_base_trainer.py
Fix of #437 
This is the command to reproduce the issue (or its resolution):
```bash
python examples/randomwalks/ppo_randomwalks.py '{"train": {"tracker": "tensorboard", "logging_dir": "tensorboard-dir", "tags": ["0"], "total_steps": 1}}'
```
=> fix(base_trainer): flatten tag list for tensorboard hparams logging

.github/workflows/build.yml, setup.cfg
The latest `bitsandbytes` requires `scipy` for a `norm` calculation but does not make it a dependency.
=> hotfix(bnb): install `scipy` with `bitsanbytes` to avoid `ModuleNotFoundError`

trlx/pipeline/offline_pipeline.py
=> fix type hint in PromptPipeline.__init__

trlx/models/modeling_ilql.py
This PR fixes an indexing error when using a single q-head instead of two.
To reproduce the error on main: `python examples/randomwalks/ilql_randomwalks.py '{"method": {"two_qs": false}}'`
https://wandb.ai/sorry/trlx/reports/Single-Q-vs-two-Qs-on-randomwalks--Vmlldzo0MzA2NTc2
=> fix(modeling_ilql): single q-head indexing

trlx/trainer/accelerate_base_trainer.py, trlx/trainer/accelerate_ppo_trainer.py
This PR 
- forces `use_cache` in `gen_kwargs` to be true by default
- replaces `batch_size` to `chunk_size` in evaluation pipeline, mirroring `make_experience` pipeline usage
- removes enforcement on padding token to be the same as endoftext with decoder models
https://wandb.ai/sorry/trlx-references/reports/fix-default-gen_kwargs-v-main--Vmlldzo0NzIwNzc2
(note that pythia run is absent because there are only 40gb gpus available currently)
=> fix(ppo_trainer): default gen kwargs

trlx/models/modeling_base.py
Parent directory not found error occurs in ppo training, because `torch.save` won't handle the save path for us(https://github.com/pytorch/pytorch/issues/71389).
=> fix(modeling_base): handle parent directory for peft head save

trlx/trainer/accelerate_base_trainer.py
peft config is not supported by tensorboard add hyperparameters. So we parse it to string.
=> fix peft config cause tensorboard type error

trlx/trainer/accelerate_base_trainer.py
Fix for https://github.com/CarperAI/trlx/pull/514#discussion_r1268935612
=> Fix: rename model_tok to tokenizer is reward_fn arg

trlx/models/modeling_ppo.py, trlx/trainer/accelerate_base_trainer.py, trlx/trainer/accelerate_ppo_trainer.py
Fix of #461 #483
Under zero3 the reference head will be kept unsharded. I couldn't get sharding to work because deepspeed expects sharded parameters to have at least one backward pass, while there is no backward pass for the reference head.
Check:
```bash
accelerate launch --config_file configs/accelerate/zero3.yaml examples/ppo_sentiments.py
```
https://wandb.ai/sorry/trlx-references/reports/fix-ppo-zero3-v-main--Vmlldzo0NjY3MDYy
=> fix(modeling_ppo): load reference head under zero3

trlx/trainer/accelerate_base_trainer.py, trlx/trainer/accelerate_ilql_trainer.py, trlx/trainer/accelerate_ppo_trainer.py, trlx/trainer/accelerate_sft_trainer.py
Suppose you have 256 rollouts, and you batch them into batches B1, B2, B3, B4 (each of size 64). The order of gradient updates (assuming 3 ppo_epochs) is:
`trlx: B1 B1 B1 B2 B2 B2 B3 B3 B3 B4 B4 B4`
However, what we should actually be doing (and what alpaca-farm and other rlhf implementations, and standard implementations of PPO do), is
`optimal: B1 B2 B3 B4 B1' B2' B3' B4' B1* B2* B3* B4*`
This change reorders the learning to make the code use the `optimal` ordering above. It also renames n_updates_per_batch to n_inner_epochs as that's a more accurate description (especially now), adjusts forward_time and backward_time to not type-error, and renames mbs and mb to minibatch and microbatch (as that's what they are).
=> Fix ordering of ppo epoch iteration

trlx/utils/modeling.py
This fixes the input embedding changing when it should be frozen when using tied embeddings by freezing the output embedding.
=> Freeze "output" embedding when using tied embeddings.

trlx/trainer/accelerate_base_trainer.py, trlx/trainer/accelerate_ppo_trainer.py
This PR
- overrides `base_trainer`'s `save_pretrained` just saving the base model inside `*WithHydraValueHead` wrapper `state_dict`
- let trainers always use `save_pretrained` for intermediate checkpoints in `ckpts/checkpoint_000d/hf_model` regardless of the `save_optimizer`'s value (for conveniency, will duplicate model weights if set to true)
Fix of #549
=> revert(ppo_trainer): keep `save_pretrained` only over the base model

trlx/models/modeling_base.py
Fix of #564, #567
This PR initializes `model.forward_kwargs` after PEFT wrapper initialization. Previously it was stuck into `model.post_init` which was never executed under PEFT.
[W&B run](https://wandb.ai/sorry/trlx/runs/8v0o4w7l)
=> fix(modeling_base): re-order `model.forward_kwargs` initialization

trlx/data/configs.py, trlx/trainer/accelerate_base_trainer.py, trlx/trainer/accelerate_ilql_trainer.py, trlx/trainer/accelerate_ppo_trainer.py, trlx/trainer/accelerate_rft_trainer.py, trlx/trainer/accelerate_sft_trainer.py
Currently, no extra configs (args in `from_pretrained` function, like `trust_remote_code`) are supported in accelerate trainer, which makes SFT/RLHF not impossible for models like baichuan/internlm etc.
So, extra model/tokenizer configs should be customizable.
=> support extra model and tokenizer configs during loading by from_pretrained in accelerate trainer
