configs/ilql_config.yml, examples/ilql_randomwalks.py, examples/ilql_sentiments.py, trlx/data/ilql_types.py, trlx/data/method_configs.py, trlx/model/accelerate_ilql_model.py, trlx/model/nn/ilql_models.py, trlx/orchestrator/offline_orchestrator.py, trlx/pipeline/offline_pipeline.py
ilql + sentiments & shortest graph's paths
=> stage ilql

CONTRIBUTING.md
* This PR adds a contribution guide to improve community standards.
* CC @shahbuland in case you want to add a building-the-docs section to the guide. (See [this](https://scikit-learn.org/dev/developers/contributing.html#building-the-documentation) for an example.)
=> [docs] Add `CONTRIBUTING.md`

configs/ppo_gptj.yml
=> [fix] Remove stale options from `ppo_gptj.yml`

trlx/model/nn/ilql_models.py
=> ILQL indicies on wrong device 

trlx/data/configs.py
Simplification of merging config logic
=> Simplifying logic to merge configs

trlx/utils/__init__.py
This pr will grant each process to have a seed of its own
Tested with `accelerate==0.15.0`
[PPO difference](https://wandb.ai/sorry/public/reports/Fix-seeding-per-process-141---VmlldzozMTcwMjgz)
=> Fix seeding per process

examples/summarize_rlhf/trlx_inference_gptj.py
* Fix inference paths to load the PPO-trained models instead of SFT checkpoints.
=> Fix `summarize_rlhf` inference checkpoint paths

trlx/trainer/nn/ilql_models.py, trlx/trainer/nn/ppo_models.py, trlx/utils/modeling.py
This PR forces value heads to be the same `dtype` as the rest of the base model
https://wandb.ai/sorry/trlx/reports/Fix-heads-dtype--VmlldzozMzk3OTM3
=> Make `make_head` accept dtype parameter

examples/summarize_rlhf/README.md
* Removes stale results description - refer to the `wandb` report for details.
CC @PhungVanDuy
=> Update stale comment from results table

trlx/trainer/accelerate_base_trainer.py
Re-introduces optional tracking after #209
=> Make experiment tracking optional

examples/summarize_rlhf/README.md
Fixes #240 (we came across this during the review of the example's PR but apparently the fix never got merged)
=> Update link to "Learning to Summarize from Human Feedback"

trlx/orchestrator/ppo_orchestrator.py, trlx/trainer/accelerate_base_trainer.py
Fix of https://github.com/CarperAI/trlx/issues/251 partial fix of https://github.com/CarperAI/trlx/issues/248, cherry picked from https://github.com/CarperAI/trlx/commit/9745ec360ee43cafd3b63f213dbf04ca212e5e35
https://wandb.ai/sorry/trlx/reports/Fix-empty-elements--VmlldzozNDczNjUz
=> Filter out empty responses

README.md
- Updates repo `README.md` to include NeMo support information in the first header subsection.
- Run markdown formatting.
=> Add `NeMo` support info to `README`

README.md
Code adapted from the [sentiment example](https://github.com/CarperAI/trlx/blob/main/examples/ilql_sentiments.py) and the [simulacra Colab](https://colab.research.google.com/drive/1vrmCLoHNlKvDVqJjMig-8tKDCfIEoym4?). One notable addition is the final cell which allows the user to see outputs from the RLHFed model. (Not sure why most of the tokens have a superfluous 'Ġ'.)
=> Add Colab Notebook for Sentiment

examples/summarize_rlhf/README.md, examples/summarize_rlhf/configs/default_accelerate_config.yaml
Fix for the first part of this comment https://github.com/CarperAI/trlx/pull/279#issuecomment-1422546283 thanks @xwwwwww for finding it
=> [fix] Summarize config discrepancy

setup.cfg
=> Release: v0.5.0

trlx/trlx.py
=> Remove logit_mask unused argument

examples/summarize_rlhf/trlx_gptj_text_summarization.py
=> hot-fix: update PPOConfig import in examples

configs/accelerate/ddp.yaml, configs/accelerate/zero2-bf16.yaml, configs/accelerate/zero2-fp16.yaml, configs/accelerate/zero3.yaml, examples/hh/ppo_hh.py, examples/hh/to_triton.py, examples/ppo_sentiments.py, examples/summarize_rlhf/configs/default_accelerate_config.yaml, examples/summarize_rlhf/trlx_gptj_text_summarization.py, examples/summarize_rlhf/trlx_inference_gptj.py, trlx/ray_train/accelerate_trainer.py, trlx/ray_train/launch.py
This PR fixes an issue with Accelerate device being mismatched when using the Ray Train integration, and updates to accelerate>=0.17.0 to remove a lot of unnecessary code.
=> [Ray Train Integration] Fix device mismatch, update to accelerate>=0.17.0

trlx/trainer/accelerate_ppo_trainer.py
This PR corrects updates for `AdaptiveKLController`, and adds logging of a square root of an estimate of `D_KL(pi || pi_ref)`
https://wandb.ai/sorry/trlx-references/reports/fix-kl-controller-v-main--VmlldzozNzM2Mzg0
PPO runs start to diverge against references precisely at the point when KL exceeds the controller's target and its scalar multiplier increases, whereas previously the same target value would not be reached.
=> [fix] Update `AdaptiveKLController` with correct KL

trlx/trainer/accelerate_ppo_trainer.py
Fixes error `cuda-exp-vml not implemented for half on cpu`
PPO Sentiments: https://wandb.ai/dahoas/trlx/runs/ycl8x4h6/overview?workspace=user-dahoas
=> fixes half exp not implemented error

examples/ppo_sentiments_llama.py, trlx/models/modeling_ppo.py, trlx/trainer/accelerate_base_trainer.py, trlx/trainer/accelerate_ppo_trainer.py, trlx/utils/modeling.py
Add LLaMa Model to trlx this PR handling with PPO algorithm
Wandb sentiment: https://wandb.ai/pvduy/trlx/runs/rtyfu6tb?workspace=user-pvduy
=> [feat] Add LLaMa Model support for PPO

examples/nemo_ilql_sentiments.py, trlx/trainer/nemo_ilql_trainer.py
Update the nemo ilql make_experience function to reuse the accelerate one. I forgot to update it with the hypothesis test additions. Also the yaml -> python config change accidently set the default beta for generations for nemo_ilql_sentiments to 4, when previously it was 2, as well as changed the temperature. This restores the previous results (although it is task specific tuning for ILQL)
https://wandb.ai/uwu1/trlxnemo/reports/make-experience-change--VmlldzozOTI3MDU5
=> Nemo ILQL fixes

setup.cfg
=> Release: v0.6.0

trlx/models/modeling_ppo.py
This PR updates the LLaMA PPO implementation to reflect recent changes in the `transformers`  [`modeling_llama.py`](https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/modeling_llama.py) code, particularly in the use of `position_ids` in the `forward` pass.
Issue: #416
Report: https://wandb.ai/carperai/trlx/reports/trlx-fix-llama-add-position_ids-to-LlamaModelBranch-418--VmlldzozOTY4MDcx
=> [fix] add `position_ids` to `LlamaModelBranch`

setup.cfg
Close https://github.com/CarperAI/trlx/issues/457
=> Pin transformers<=4.27.1

trlx/trainer/accelerate_base_trainer.py
=> docs(base_trainer): fill in missing `prepare_learning` method

trlx/models/modeling_ppo.py
=> fix(modeling_ppo): invert padding percentage calculation

setup.cfg
=> Release: v0.7.0

trlx/models/modeling_ppo.py
`GPTBigCodeModelBranch` support [bigcode models family](https://huggingface.co/bigcode), such as:
* https://huggingface.co/bigcode/starcoder
* https://huggingface.co/bigcode/starcoderbase
* etc..
=> feat(modeling_ppo): add GPTBigCodeModelBranch

README.md
This PR adds a small note explaining which config parameters affect the memory usage, while previously it wasn't obvious which should be tweaked and how in order to avoid out of memory issues.
Fix of #372, #459
=> feat(readme): add instructions to avoid OOMs with hyperparameters

examples/ppo_sentiments_llama.py, requirements.txt
WanDB Run: https://wandb.ai/pvduy/trlx/runs/07gr53v1
=> Fix LLaMA example (LLaMA 2)

trlx/models/modeling_ppo.py, trlx/trainer/accelerate_ppo_trainer.py
Introduces `num_value_layers_unfrozen` model parameter
=> Value branch

examples/summarize_daily_cnn/t5_summarize_daily_cnn.py
Fix of #569
W&B: https://wandb.ai/sorry/trlx/runs/icjycjk2
=> fix(examples/t5_summarize_cnn): move labels into `reward_fn` kwargs

trlx/models/modeling_base.py
This PR fixes `PreTrainedModelWrapper`'s `from_pretrained`, letting it load all sharded checkpoints, instead of only ones containing `_supported_modules` states
=> fix(modeling_base): partial loading of a sharded checkpoint
